[project]
name = "metadate-renamer"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "hachoir>=3.3.0",
    "pillow>=11.3.0",
    "pyside6>=6.9.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.14.2",
]
